# Generated by Django 6.0.4 on 2026-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='My POS Shop', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logo/')),
                ('footer_receipt', models.TextField(default='Thank You! Please come again.', help_text='ဘောက်ချာအောက်ဆုံးမှာ ပေါ်မယ့်စာ')),
            ],
            options={
                'verbose_name': 'Shop Setting',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
    ]
