# Generated by Django 6.0.4 on 2026-05-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shopsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsetting',
            name='currency',
            field=models.CharField(default='MMK', max_length=20),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='low_stock_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='tax_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
